sudo: false

language: java

jdk:
- oraclejdk8

env:
  global:
    - secure: "IfYURwZaDWuBDvyn47n0k1Zod/IQw1FF+CS5nnV08Q+NfC3vGGJMwV8m59XnbfwnWGxwvCaAbk4qP6s6+ijgZNKkvgfFMo3rfTok5zt43bIqgaFOANYV+OC/1c59gYD6ZUxhW5iNgMgU3qdsRtJuwSmfkVv/jKyLGfAbS4kN8BA=" #coverity

script: mvn -fmain/pom.xml -Ptest-coverage clean test jacoco:report-aggregate

after_success:
- "bash <(curl -s https://codecov.io/bash)"

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7d429ab35361726e26f2
    on_success: change
    on_failure: always
    on_start: false
  slack:
    rooms:
      secure: "lngJ/HEAFBbD5AdiO9avMqptKpZHdmEwOzS9FabZjkdFh7yAYueTk5RniPUvShjsKtThYm7cJ8AtDMDwc07NvPrzbMBRtUJGwuDT+7c7YFALGFJ1NYi+emkC9x1oafvmPgEYSE+tMKzNcwrHi3ytGgKdIotsKwaF35QNXYA9aMs="
    on_success: change
    on_failure: always

before_deploy: mvn -fmain/pom.xml -Prelease clean package -DskipTests

addons:
  coverity_scan:
    project:
      name: "cryptomator/cryptomator"
    notification_email: sebastian.stenzel@cryptomator.org
    build_command: "mvn -fmain/pom.xml clean test -DskipTests"
    branch_pattern: release.*

deploy:
  provider: releases
  prerelease: false
  api_key:
    secure: "ZjE1j93v3qbPIe2YbmhS319aCbMdLQw0HuymmluTurxXsZtn9D4t2+eTr99vBVxGRuB5lzzGezPR5zjk5W7iHF7xhwrawXrFzr2rPJWzWFt0aM+Ry2njU1ROTGGXGTbv4anWeBlgMxLEInTAy/9ytOGNJlec83yc0THpOY2wxnk="
  file:
    - "main/uber-jar/target/Cryptomator-$TRAVIS_TAG.jar"
    - "main/ant-kit/target/antkit.tar.gz"
  skip_cleanup: true
  on:
    repo: cryptomator/cryptomator
    tags: true
